// Wraps the compiled VeilVote contract (generated by `npm run compact` into
// ../../managed) into the `CompiledContract` binding that
// `deployContract`/`findDeployedContract` require. The witnesses are the same
// ones used by the Node test simulator, applied here to the browser voter's
// currently-selected identity instead of a fixed test key.
import * as CompiledContract from "@midnight-ntwrk/compact-js/effect/CompiledContract";
import { Contract } from "../../../managed/contract/index.js";
import type { WitnessContext } from "@midnight-ntwrk/compact-runtime";
import type { Ledger } from "../../../managed/contract/index.js";
import type { VeilVotePrivateState } from "./types.js";

const witnesses = {
  voterSecretKey: ({
    privateState,
  }: WitnessContext<Ledger, VeilVotePrivateState>): [VeilVotePrivateState, Uint8Array] => [
    privateState,
    privateState.secretKey,
  ],
  merkleSiblings: ({
    privateState,
  }: WitnessContext<Ledger, VeilVotePrivateState>): [VeilVotePrivateState, Uint8Array[]] => [
    privateState,
    privateState.merkleSiblings,
  ],
  merklePathIndices: ({
    privateState,
  }: WitnessContext<Ledger, VeilVotePrivateState>): [VeilVotePrivateState, boolean[]] => [
    privateState,
    privateState.merklePathIndices,
  ],
};

// The "compiled assets path" below is a required tag for the CompiledContract
// binding; the actual ZK artifact bytes are fetched at runtime over HTTP by
// the FetchZkConfigProvider configured in providers.ts (see that file for why).
export const veilVoteCompiledContract = CompiledContract.make<
  Contract<VeilVotePrivateState>
>("VeilVote", Contract).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets("contract"),
);

// The one provable (on-chain) circuit exposed by the compiled contract.
export type VeilVoteCircuitId = "castVote";
